# Librerías a utilizar ---------------------------------------------------------
library(dplyr)
library(lubridate)
library(readr)
library(tidyverse)
library(writexl)
library(ggplot2)
library(plotly)
library(scales)
library(shiny)
library(shinyWidgets)
library(shinythemes)
library(DT)
library(sf)
library(leaflet)
library(spData)
library(leaflet)